// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalaryManager.Data;

#nullable disable

namespace SalaryManager.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260531072609_AddEmployeeOptionalFieldsAndTdsOverride")]
    partial class AddEmployeeOptionalFieldsAndTdsOverride
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("SalaryManager.Data.Entities.Advance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntryType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceKey")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Date", "Id");

                    b.HasIndex("EmployeeId", "Date");

                    b.HasIndex("EmployeeId", "SourceKey")
                        .IsUnique();

                    b.HasIndex("SourceKey", "EntryType", "EmployeeId");

                    b.ToTable("Advances");
                });

            modelBuilder.Entity("SalaryManager.Data.Entities.AttendanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("BaseSalaryOverride")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<int>("DaysAbsent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EsicDeduction")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<bool>("IsTdsManualOverride")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("NetSalaryOverride")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<decimal>("PfDeduction")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<decimal>("TdsDeduction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "Year", "Month")
                        .IsUnique();

                    b.HasIndex("Year", "Month", "EmployeeId");

                    b.ToTable("AttendanceRecords");
                });

            modelBuilder.Entity("SalaryManager.Data.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AadharNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BaseSalary")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IfscCode")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("InsuranceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("JoiningDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("UanNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "Name");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("SalaryManager.Data.Entities.EmployeeGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("EmployeeGroups");
                });

            modelBuilder.Entity("SalaryManager.Data.Entities.EmployeeGroupMembership", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeGroupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EmployeeId", "EmployeeGroupId");

                    b.HasIndex("EmployeeGroupId", "EmployeeId");

                    b.ToTable("EmployeeGroupMemberships");
                });

            modelBuilder.Entity("SalaryManager.Data.Entities.SalaryRevision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("NewSalary")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OldSalary")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("EmployeeId", "ChangedAt");

                    b.ToTable("SalaryRevisions");
                });

            modelBuilder.Entity("SalaryManager.Data.Entities.Advance", b =>
                {
                    b.HasOne("SalaryManager.Data.Entities.Employee", "Employee")
                        .WithMany("Advances")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SalaryManager.Data.Entities.AttendanceRecord", b =>
                {
                    b.HasOne("SalaryManager.Data.Entities.Employee", "Employee")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SalaryManager.Data.Entities.EmployeeGroupMembership", b =>
                {
                    b.HasOne("SalaryManager.Data.Entities.EmployeeGroup", "EmployeeGroup")
                        .WithMany("Memberships")
                        .HasForeignKey("EmployeeGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalaryManager.Data.Entities.Employee", "Employee")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("EmployeeGroup");
                });

            modelBuilder.Entity("SalaryManager.Data.Entities.SalaryRevision", b =>
                {
                    b.HasOne("SalaryManager.Data.Entities.Employee", "Employee")
                        .WithMany("SalaryRevisions")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SalaryManager.Data.Entities.Employee", b =>
                {
                    b.Navigation("Advances");

                    b.Navigation("AttendanceRecords");

                    b.Navigation("GroupMemberships");

                    b.Navigation("SalaryRevisions");
                });

            modelBuilder.Entity("SalaryManager.Data.Entities.EmployeeGroup", b =>
                {
                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
